# deploy.yml
- name: Build, Push, and Deploy Docker Image
  hosts: localhost  # Use localhost to build and push; use target server to deploy
  become: true
  vars:
    image_name: "eladwy/firstproject"
    image_tag: "latest"
    container_name: "my-app"
    docker_hub_username: "{{ lookup('env', 'abdelrahman.aeladwy@gmail.com') }}"
    docker_hub_password: "{{ lookup('env', 'Jpia331##') }}"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Build the Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "."

    - name: Push the Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes

- name: Deploy Docker Container
  hosts: localhost
  become: true
  vars:
    image_name: "eladwy/firstproject"
    image_tag: "latest"
    container_name: "my-app"

  tasks:
    - name: Pull Docker Image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Stop and remove existing container (if running)
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Run the Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "80:80"
